version: "3.9"

services:
  api:
    build: .
    container_name: sigetu_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./sigetu-b10c0-firebase-adminsdk-fbsvc-d3c8e11eaf.json:/app/sigetu-b10c0-firebase-adminsdk-fbsvc-d3c8e11eaf.json:ro

  db:
    image: postgres:16-alpine
    container_name: sigetu_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2101"
      POSTGRES_DB: sigetu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
