"""add_device_id_and_nullable_student_id_to_appointments

Revision ID: cc49122692e7
Revises: 0ef4a793bf9c
Create Date: 2026-03-07 18:56:00.965857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc49122692e7'
down_revision: Union[str, Sequence[str], None] = '0ef4a793bf9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('device_id', sa.String(length=36), nullable=True))
    op.alter_column('appointments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_appointments_device_id'), 'appointments', ['device_id'], unique=False)
    op.create_check_constraint(
        'ck_appointments_owner',
        'appointments',
        "(student_id IS NULL) != (device_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_appointments_owner', 'appointments', type_='check')
    op.drop_index(op.f('ix_appointments_device_id'), table_name='appointments')
    op.alter_column('appointments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'device_id')
    # ### end Alembic commands ###
